version: '3'
services:
  db:
    restart: always
    image: postgres:9.6.3
    expose:
      - "5432"
    ports:
      - "5400:5432"

    environment:
      POSTGRES_DB: "system"
      POSTGRES_USER: "dbadmin"
      POSTGRES_PASSWORD: "changeme"

#  redis:
#    image: redis:3.2.4-alpine
#    ports:
#      - "${REDIS_PORT}:6379"
#
#  sign-proxy:
#    image: codekoala/aws-sign-proxy:v0.1.3
#    environment:
#      AWS_ACCESS_KEY_ID: "${LOANPAL_ACCESS_KEY_ID}"
#      AWS_SECRET_ACCESS_KEY: "${LOANPAL_SECRET_ACCESS_KEY}"
#      AWS_SIGN_PROXY_TARGETHOST: "${AWS_SIGN_PROXY_TARGETHOST}"
#      AWS_SIGN_PROXY_PROVIDER: "${AWS_SIGN_PROXY_PROVIDER}"
#      AWS_SIGN_PROXY_REGION: "${AWS_SIGN_PROXY_REGION}"
#      AWS_SIGN_PROXY_BLOCKHEADERS: "connection"
#    ports:
#      - "8081:8080"
